# A human-readable description for the state machine.
Comment: "Optional: A brief description of what this state machine does."

# The NAME of the IAM role that AWS Step Functions will assume to execute the state machine.
# The module will construct the full ARN using this name and the current AWS Account ID.
# Example: "MyStepFunctionsExecutionRole"
RoleName: "MyStepFunctionsExecutionRole"

# The relative path from this YAML file to the JSON file containing the Amazon States Language (ASL) definition.
# This definition will be processed by Terraform's "templatefile" function.
DefinitionPath: "./state-machines/definitions/my-definition.json"

# A map of variables to be substituted into the DefinitionPath JSON file.
# These values can also be templated from the main variables.
DefinitionVariables:
  S3_BUCKET_NAME: "orders-bucket-${environment}"
  DATABASE_TABLE: "orders-table-${environment}"
  NOTIFICATION_TOPIC_ARN: "${notification_arn}"

# Defines how the state machine is triggered. You must specify either Cron or EventPattern.
Trigger:
  # A schedule for recurring executions, defined using a cron expression.
  # Example: "cron(0 20 * * ? *)" to run at 8:00 PM (UTC) every day.
  Cron: "cron(0 20 * * ? *)"
  
  # An Amazon EventBridge pattern to trigger the state machine based on specific events.
  # This example triggers on a new object in a specific S3 bucket.
  EventPattern: |
    {
      "source": ["aws.s3"],
      "detail-type": ["Object Created"],
      "detail": {
        "bucket": {
          "name": ["my-special-bucket"]
        }
      }
    }

# Optional: Configuration for CloudWatch Logs.
LoggingConfiguration:
  # The level of logging. Can be ALL, ERROR, or FATAL. Defaults to OFF if not specified.
  Level: "ALL"
  # Determines whether execution data is included in the logs. Defaults to false.
  IncludeExecutionData: true

# Optional: Enables AWS X-Ray tracing for performance monitoring and debugging.
TracingConfiguration:
  Enabled: true

# Optional: A map of key-value pairs to tag the state machine resource.
Tags:
  Project: "Phoenix"
  Owner: "DataEngineering"
  Environment: "Development"