#
# S3 Bucket Configuration for: my-app-logs-bucket
# This bucket stores application logs for the project "${ProjectName}".
#

# (Optional) Enables versioning to protect against accidental data loss.
# Default: false
VersioningEnabled: true

# (Optional) Allows deletion of the bucket even if it contains objects.
# Set to true in dev/test environments. For production, this should be false.
# Default: false
ForceDestroy: false

# (Optional) Tags for cost tracking and resource management.
# The 'Environment' tag will be substituted by the Terraform module.
Tags:
  Project: "${ProjectName}"
  Environment: "${Environment}"
  ManagedBy: "Terraform"

# (Optional) Lifecycle rules to manage object storage costs and retention.
LifecycleRules:
  - Id: "log-archival-rule"
    Enabled: true
    Prefix: "logs/" # This rule applies only to objects under the 'logs/' prefix.

    # Transition logs to Infrequent Access storage after 30 days.
    Transitions:
      - Days: 30
        StorageClass: "STANDARD_IA"
      # Transition logs to Glacier Instant Retrieval after 90 days.
      - Days: 90
        StorageClass: "GLACIER_IR"

    # Permanently delete logs after 1 year (365 days).
    Expiration:
      Days: 365

    # Clean up any failed multipart uploads after 7 days.
    AbortIncompleteMultipartUploadDays: 7

# (Optional) Server-side encryption configuration.
ServerSideEncryption:
  Rule:
    ApplyServerSideEncryptionByDefault:
      # Use AWS-managed keys for encryption.
      SseAlgorithm: "AES256"

# (Optional) Block all public access to this bucket.
# Highly recommended for security.
PublicAccessBlock:
  BlockPublicAcls: true
  BlockPublicPolicy: true
  IgnorePublicAcls: true
  RestrictPublicBuckets: true

# This bucket is not used for static website hosting, so the 'Website'
# section is omitted.